apiVersion: v1
kind: Service
metadata:
  name: ${appName}-service
spec:
  type: ${serviceType}
  selector:
    app: ${appName}
  ports:
    - protocol: TCP
      port: ${port}
      targetPort: ${port}
      nodePort: ${nodePort}
