name: .NET Core CI

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: [self-hosted, Linux, X64, nonprod-runner]
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::142146926157:role/GH_test
          aws-region: eu-west-1
          mask-aws-account-id: false

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.301
      - name: Install dependencies
        run: |
          UBUNTU_VERSION=$(lsb_release -cs)
          echo "deb http://security.ubuntu.com/ubuntu $UBUNTU_VERSION-security main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install libssl1.0.0
          wget https://packages.microsoft.com/config/ubuntu/$UBUNTU_VERSION/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y aspnetcore-runtime-5.0


      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

  Deploy:
    runs-on: [self-hosted, Linux, X64, nonprod-runner]
    needs: Build

    strategy:
      matrix:
        dotnet-version: ['5.0.301', '7.0.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
