name: .NET Core CI

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: [self-hosted, Linux, X64, nonprod-runner]
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::142146926157:role/GH_test
          aws-region: eu-west-1
          mask-aws-account-id: false
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.315
      - name: Install dependencies
        run: |
          UBUNTU_VERSION=$(lsb_release -cs)
          #echo "deb http://security.ubuntu.com/ubuntu $UBUNTU_VERSION-security main" | sudo tee -a /etc/apt/sources.list
          #sudo apt-get update
          #sudo apt-get install libssl1.0.0
          #sudo apt-get update
          #sudo apt-get install -y aspnetcore-runtime-5.0

      - name: Dotnet Restore
        run: |
          ls -la
          pwd
          cd dotnetcore-app
          dotnet restore

      - name: Build
        run: |
          cd dotnetcore-app
          dotnet build --configuration Release --no-restore

  Deploy:
    runs-on: [self-hosted, Linux, X64, nonprod-runner]
    needs: Build

    strategy:
      matrix:
        dotnet-version: ['6.0.315']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.315

      - name: Install dependencies
        run: |
          ls -la
          pwd
          cd dotnetcore-app
          dotnet restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
